name: Generate HTML script paragraph

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Link to the script'
        required: true
      date:
        description: 'Date of the script'
        required: true

jobs:
  generate-output:
    runs-on: ubuntu-latest

    steps:
    - name: Generate output
      run: |
        OUTPUT="<p><a href=\"${{ github.event.inputs.link }}\" target=\"_blank\">This</a> is our current script as of <strong>${{ github.event.inputs.date }}</strong>. We keep changing documents, so this might not be up to date. <p><br>"
        echo "Output: $OUTPUT"
